### ISSUE TITLE
Document mandelbrot navigation configuration option

### ISSUE THREAD

**Issue by mihkeleidast** [samuelgoddard/fractal-docs#107]
https://github.com/frctl/fractal/pull/1100

**Comment by julkue** [comment]
I'm glad I found this issue :-) I thought that the now appearing `navigation type: default` is a bug on my end, because it's a little strange that this is shown in the header if the user can't change it. Why is it shown by the way? The other options that a dev has specified aren't shown either.

**Comment by mihkeleidast** [comment]
@julmot uhh sorry, that is a bug. can you send a PR to remove that? https://github.com/frctl/fractal/pull/1100/files#diff-45df616b66919441455f6ec9c62faa5f7d51d4bf0585736297b33f6dc7777181R11

**Comment by mihkeleidast** [comment]
@julmot that _bug_ should be fixed in the latest release, sorry again!

**Comment by mihkeleidast** [comment]
Resolved in #108.
